### ISSUE TITLE
似乎 bot 已经不能用了

### ISSUE THREAD

**Issue by OnAKnifeEdge** [genelocated/telegram-find-in-channel-bot#3]
前两天忽然坏掉了。restart 没有用。请问可以修复吗？谢谢！

**Comment by chuangzhu** [comment]
我也遇到了，但重启后就正常了。请问可以将失败的 log 贴出来吗？

**Comment by OnAKnifeEdge** [comment]
啊我也试了重启没有用。我直接用的 tg 上的 bot 不是自己部署的。所以不大清楚在哪里可以看到 log? 可以指条路吗？谢谢！

**Comment by chuangzhu** [comment]
那个是部署在我的服务器上的。我之前误操作把服务关了，现在应该可以正常使用了。

**Comment by OnAKnifeEdge** [comment]
哇！可以用了！谢谢大神！感恩！
