### ISSUE TITLE
Can't start bot 

### ISSUE THREAD

**Issue by Kadiya99** [genelocated/telegram-find-in-channel-bot#5]
I'm using debian server. 
Using mariadb for db

When I try to /start in bot it's showing this error

  File "/root/telegram-find-in-channel-bot/tgficbot/i18n.py", line 25, in wrapper
    if user.lang_code in translates else translates['en']
KeyError: 'en'

can you help me for this

**Comment by chuangzhu** [comment]
Are you running it from source? Please use the following commands to generate translate files (as documented in README):

```bash
cd telegram-find-in-channel-bot
for f in tgficbot/locales/*.po; do
    mkdir -p ${f%.po}/LC_MESSAGES
    msgfmt $f -o ${f%.po}/LC_MESSAGES/main.mo
done
```
